"""
CodeWhisper — HintLog Model
Records every hint delivered to a user during a problem session.

Table: hint_logs
Relationships:
    - Many hint logs → one UserProblemSession (backref: 'session')
"""

import uuid
from datetime import datetime, timezone
from app.extensions import db


class HintLog(db.Model):
    __tablename__ = "hint_logs"

    # ── Primary Key ───────────────────────────────────────────────────────────
    id = db.Column(
        db.UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False
    )

    # ── Foreign Key ───────────────────────────────────────────────────────────
    session_id = db.Column(
        db.UUID(as_uuid=True),
        db.ForeignKey("user_problem_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # ── Fields ────────────────────────────────────────────────────────────────
    # Hint depth: 1 = vague nudge → 5 = near-complete approach
    hint_level = db.Column(db.Integer, nullable=False)

    # The actual hint text generated by the LLM
    hint_text = db.Column(db.Text, nullable=False)

    delivered_at = db.Column(
        db.DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    # ── Table Constraints ─────────────────────────────────────────────────────
    __table_args__ = (
        # Ensure each session can only have one entry per hint level
        db.UniqueConstraint("session_id", "hint_level", name="uq_session_hint_level"),
    )

    # ── Repr ──────────────────────────────────────────────────────────────────
    def __repr__(self):
        return (
            f"<HintLog id={self.id} session_id={self.session_id} "
            f"hint_level={self.hint_level}>"
        )

    # ── Serialization ─────────────────────────────────────────────────────────
    def to_dict(self):
        """Return dict representation for API responses."""
        return {
            "id": str(self.id),
            "session_id": str(self.session_id),
            "hint_level": self.hint_level,
            "hint_text": self.hint_text,
            "delivered_at": self.delivered_at.isoformat() if self.delivered_at else None,
        }
